## Saving master knowledge base

### Reading the `jsonl` knowledge base files.
We have 3 knowledge bases. 

In [ ]:
def filter_jsonl(jsonl):
    """
    Returns True if this is the kind of jsonl 
    that we want in our master kb
    """
    if len(item['paragraph'].split()) < 50:
        return False
    return True

In [8]:
import json_lines
from pprint import pprint

with open('../data/blueletterbible.jsonl', 'rb') as f:
    for item in json_lines.reader(f):
        if len(item['paragraph'].split()) < 50:
            pprint(item)

        

{'authors': 'Macarthur John',
 'document_nm': ' - Bible Introductions - Genesis',
 'paragraph': 'The literary structure of Genesis is built on the frequently '
              'recurring phrase “the history/genealogy of” and is the basis '
              'for the following outline:',
 'url': 'https://www.blueletterbible.org/Comm/macarthur_john/bible-introductions/genesis-intro.cfm',
 'verse_reference': ''}
{'authors': 'Macarthur John',
 'document_nm': ' - Bible Introductions - Genesis',
 'paragraph': 'This Grace to You article originally appeared here.         '
              'Copyright 2007, Grace to You. All rights reserved. Used by '
              'permission.',
 'url': 'https://www.blueletterbible.org/Comm/macarthur_john/bible-introductions/genesis-intro.cfm',
 'verse_reference': ''}
{'authors': 'Macarthur John',
 'document_nm': ' - Bible Introductions - Exodus',
 'paragraph': '1. LXX Septuagint: an ancient translation of the Old Testament '
              'into Greek.',
 'url': 'https

 'verse_reference': ''}
{'authors': 'Macarthur John',
 'document_nm': ' - Bible Introductions - Galatians',
 'paragraph': 'This Grace to You article originally appeared here.        '
              'Copyright 2007, Grace to You. All rights reserved. Used by '
              'permission.',
 'url': 'https://www.blueletterbible.org/Comm/macarthur_john/bible-introductions/galatians-intro.cfm',
 'verse_reference': ''}
{'authors': 'Macarthur John',
 'document_nm': ' - Bible Introductions - Ephesians',
 'paragraph': 'This Grace to You article originally appeared here.        '
              'Copyright 2007, Grace to You. All rights reserved. Used by '
              'permission.',
 'url': 'https://www.blueletterbible.org/Comm/macarthur_john/bible-introductions/ephesians-intro.cfm',
 'verse_reference': ''}
{'authors': 'Macarthur John',
 'document_nm': ' - Bible Introductions - Philippians',
 'paragraph': 'Philippians derives its name from the Greek city where the '
              'church to which

 'url': 'https://www.blueletterbible.org/Comm/headley_pc/WOTB/WotB_18_The_Sisters_Martha_and_Mary.cfm',
 'verse_reference': ''}
{'authors': 'Headley Pc',
 'document_nm': ' - Dorcas',
 'paragraph': 'But all these events recede into the dimness of eclipse, around '
              'the scenes which have transpired in the dwelling of Tabitha, '
              '(Act 9:36) and which shall survive the cenotaphs of royal '
              'heroes as they successively moulder, written in the history and '
              'blending with the converse of Heaven.',
 'url': 'https://www.blueletterbible.org/Comm/headley_pc/WOTB/WotB_19_Dorcas.cfm',
 'verse_reference': ''}
{'authors': 'Headley Pc',
 'document_nm': ' - Dorcas',
 'paragraph': 'Whatever her condition, it is enough to know that she bent all '
              'her energies to imitate the faultless model of philanthropy, '
              'and extend the glory of His name by illustrating the '
              'transcendent excellence of Christian chara

 'document_nm': ' - Part 28 - Matthew 24:31 An Angelic Gathering',
 'paragraph': 'The Matthew passage is a rather simple summary of all that the '
              'prophets had to say about the second facet of Israel’s final '
              'restoration. Its purpose was to make clear that the world-wide '
              'regathering predicted by the prophets will be fulfilled only '
              'after the Second Coming.',
 'url': 'https://www.blueletterbible.org/Comm/ice_thomas/Mat24-25/Mat24-25_Part28.cfm',
 'verse_reference': ''}
{'authors': 'Ice Thomas',
 'document_nm': ' - Part 28 - Matthew 24:31 An Angelic Gathering',
 'paragraph': 'Dr. Renald Showers has done an excellent job collecting '
              'evidence and arguing for this view. After noting that “from the '
              'four winds, from one end of the sky to the other” means that '
              '“the elect will be gathered from all over the world at Christ’s '
              'coming,”',
 'url': 'https://www.blueletter

 'url': 'https://www.blueletterbible.org/Comm/ice_thomas/Mat24-25/Mat24-25_Part18.cfm',
 'verse_reference': ''}
{'authors': 'Ice Thomas',
 'document_nm': ' - Part 18 - Matthew 24:23-25 Wrongly Looking for Messiah',
 'paragraph': 'Jesus is saying in Matthew 24:23-25 two major points about '
              'false Messiahs. First, the false Messiah will not be visible '
              'and out in the open. Second, the false Messiah will do miracles '
              'in order to mislead and deceive many.',
 'url': 'https://www.blueletterbible.org/Comm/ice_thomas/Mat24-25/Mat24-25_Part18.cfm',
 'verse_reference': ''}
{'authors': 'Ice Thomas',
 'document_nm': ' - Part 18 - Matthew 24:23-25 Wrongly Looking for Messiah',
 'paragraph': '“The central point in Matthew 24:23-28 is that believers are '
              'not to be deceived by false prophets who claim to have special '
              'information about the whereabouts of the Christ,” notes Robert '
              'Mounce.',
 'url': 'https://

In [22]:
qwe = np.array([[1,1,1]])
np.vstack([qwe,qwe,qwe,qwe])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### checking the model

In [24]:
import sys
sys.path.append('..')

from src.model import GoldenRetriever

gr = GoldenRetriever()

model initiated!


In [32]:
asdd = gr.embed.signatures['response_encoder'](
    input = tf.constant(["Hi my name is all"]),
                                        context = tf.constant(["his name is all"])
                                       )

{'outputs': <tf.Tensor: id=212998, shape=(1, 512), dtype=float32, numpy=
 array([[ 3.99451517e-02,  9.91387875e-04,  6.02627452e-03,
          1.12430071e-02,  5.24175912e-02,  4.83475626e-02,
          3.70580480e-02, -3.56345437e-02, -3.01198736e-02,
         -4.97765243e-02,  4.39032800e-02, -5.83607815e-02,
          3.72476578e-02, -7.69582614e-02, -8.22309405e-02,
          2.48524901e-02, -3.75848562e-02,  2.48485487e-02,
         -4.44339626e-02,  1.77465081e-02, -3.16949934e-02,
          5.03415428e-02,  2.76511777e-02, -5.77232800e-02,
         -2.33348664e-02, -1.59744378e-02, -5.26219718e-02,
          4.58048433e-02,  4.25054133e-02,  2.83345263e-02,
          8.06748215e-03,  7.95855746e-02, -5.13274856e-02,
          5.28612174e-02,  4.53118198e-02,  5.95729835e-02,
          4.55976240e-02,  5.37599325e-02, -8.82534805e-05,
         -3.35255428e-03,  4.57373001e-02,  1.64873712e-02,
         -3.71365286e-02,  6.66625798e-03,  6.07656799e-02,
         -3.26799564e-02,  

In [36]:
asdd['outputs'].numpy()

array([[ 3.99451517e-02,  9.91387875e-04,  6.02627452e-03,
         1.12430071e-02,  5.24175912e-02,  4.83475626e-02,
         3.70580480e-02, -3.56345437e-02, -3.01198736e-02,
        -4.97765243e-02,  4.39032800e-02, -5.83607815e-02,
         3.72476578e-02, -7.69582614e-02, -8.22309405e-02,
         2.48524901e-02, -3.75848562e-02,  2.48485487e-02,
        -4.44339626e-02,  1.77465081e-02, -3.16949934e-02,
         5.03415428e-02,  2.76511777e-02, -5.77232800e-02,
        -2.33348664e-02, -1.59744378e-02, -5.26219718e-02,
         4.58048433e-02,  4.25054133e-02,  2.83345263e-02,
         8.06748215e-03,  7.95855746e-02, -5.13274856e-02,
         5.28612174e-02,  4.53118198e-02,  5.95729835e-02,
         4.55976240e-02,  5.37599325e-02, -8.82534805e-05,
        -3.35255428e-03,  4.57373001e-02,  1.64873712e-02,
        -3.71365286e-02,  6.66625798e-03,  6.07656799e-02,
        -3.26799564e-02,  2.19597556e-02, -5.31988218e-02,
         3.44779007e-02, -7.16895014e-02, -5.89885190e-0

In [37]:
# gr.predict("Hi my name is all")

In [26]:
paragraph = "IF anyone is in search of accurate information regarding the age of this earth, or its relation to the sun, moon, and stars, or regarding the order in which plants and animals have appeared upon it, he is referred to recent textbooks in astronomy, geology, and palaeontology. No one for a moment dreams of referring a serious student of these subjects to the Bible as a source of information. It is not the object of the writers of Scripture to impart physical instruction or to enlarge the bounds of scientific knowledge. But if any one wishes to know what connection the world has with God, if he seeks to trace back all that now is to the very fountain-head of life, if he desires to discover some unifying principle, some illuminating purpose in the history of this earth, then we confidently refer him to these and the subsequent chapters of Scripture as his safest, and indeed his only, guide to the information he seeks. Every writing must be judged by the object the writer has in view. If the object of the writer of these chapters was to convey physical information, then certainly it is imperfectly fulfilled. But if his object was to give an intelligible account of God’s relation to the world and to man, then it must be owned that he has been successful in the highest degree."

In [12]:
question_embeddings['outputs'].numpy()

array([[ 9.19036046e-02, -2.24868720e-03,  1.76704917e-02,
        -2.18526628e-02, -2.62343436e-02, -3.56416516e-02,
         8.46295338e-03,  1.85972173e-02, -4.40590754e-02,
        -4.32619564e-02, -1.69401113e-02,  5.73555157e-02,
         1.95370361e-04,  3.89271528e-02, -4.75711562e-02,
        -2.08302587e-02, -3.50843072e-02, -1.72923043e-01,
        -5.10371961e-02, -2.97765061e-02,  3.64540406e-02,
         1.71433180e-03,  8.39457754e-03, -6.98974030e-03,
         3.61285023e-02, -2.08084714e-02, -6.21803477e-02,
        -2.81675421e-02,  5.84245883e-02,  1.01516470e-01,
        -1.83372162e-02,  3.56718525e-02,  1.26061616e-02,
         1.50679750e-02, -6.55016154e-02, -6.02240628e-03,
        -2.00633872e-02,  4.44769599e-02, -1.05837695e-02,
        -1.71632320e-02,  8.41979589e-03,  2.31846534e-02,
        -2.84399297e-02, -2.76407599e-02,  5.23682311e-02,
         6.43531010e-02,  2.03801244e-02, -2.46584024e-02,
        -2.70023514e-02, -6.53365031e-02,  6.30521625e-0

### Connecting to sql database

In [1]:
import sqlite3 as sq
master_kb_text_dir = '../data/master_kb_text.db'
# con = sq.connect(master_kb_text_dir)

# query = 'SELECT * FROM master_kb_text'
# asddd = con.execute(query).fetchall()

In [2]:
asddd

[]

In [2]:
con = sq.connect(master_kb_text_dir)
query = 'CREATE TABLE master_kb_text (idx real, authors text, document_nm text, paragraph text, url text, verse_references text)'
con.execute(query)
con.commit() 

In [4]:
con.close()